apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-mq
  name: my-mq
spec:
  containers:
  - env:
    - name: LICENSE
      value: accept
    - name: MQ_QMGR_NAME
      value: QM1
    - name: MQ_APP_PASSWORD
      value: passw0rd
    - name: MQS_IPC_HOST
      value: mq   
    image: docker.io/ibmcom/mq:latest
    name: my-mq
    ports:
    - containerPort: 1414
      name: channel
    - containerPort: 9443
      name: web
     
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
